name: zc_desktop_flutter
description: Zuri Chat Desktop App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.0-318.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # stacked
  stacked: ^3.0.0
  stacked_services: ^0.9.8
  stacked_themes: ^0.3.9
  stacked_hooks: ^0.2.2

  # utilities
  cupertino_icons: ^1.0.5
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  google_fonts: ^3.0.1
  bitsdojo_window: ^0.1.5
  desktop_window: ^0.4.0
  intl: ^0.17.0
  flutter_hooks: ^0.18.5+1
  logger: ^1.1.0
  getwidget: ^3.0.1
  popover: ^0.2.7

  #For building otp field
  otp_text_field: ^1.1.3
  # animation
  lottie: ^2.0.0

  # local storage
  shared_preferences: ^2.0.15

  # Network calls
  dio: ^4.0.6
  dio_cache_interceptor: ^3.3.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  file_picker: ^5.2.2
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^3.0.2

  # html: ^0.14.0+3
  # http: ^0.12.1 
  any_link_preview: ^2.0.9

  whiteboard: ^0.0.1
  animated_floating_buttons: ^0.0.2
 
  # Centrifuge 
  centrifuge: ^0.9.2
  # Url Launcher
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  stacked_generator: ^0.8.0+1
  build_runner: ^2.3.2
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  mockito: ^5.3.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

    - assets/lottie/

