name: zc_desktop_flutter
description: Zuri Chat Desktop App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # stacked
  stacked: ^2.2.5
  stacked_services: ^0.8.13
  stacked_themes: ^0.3.6
  stacked_hooks: ^0.2.1

  # utilities
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^0.22.0
  google_fonts: ^2.1.0
  bitsdojo_window: ^0.1.1+1
  desktop_window: ^0.4.0
  intl: ^0.17.0
  flutter_hooks: ^0.17.0
  logger: ^1.0.0
  getwidget: ^2.0.4
  popover: ^0.2.6+2

  #For building otp field
  otp_text_field: ^1.1.1
  # animation
  lottie: ^1.1.0

  # local storage
  shared_preferences: ^2.0.7

  # Network calls
  dio: ^4.0.0
  dio_cache_interceptor: ^3.0.2
  freezed_annotation:
  json_annotation: ^4.3.0
  file_picker: ^4.1.1
  internet_connection_checker: ^0.0.1+2
  connectivity_plus: ^1.4.0

  # html: ^0.14.0+3
  # http: ^0.12.1 
  any_link_preview: ^2.0.1-rc

  whiteboard: ^0.0.1
  animated_floating_buttons: ^0.0.2
 
  # Centrifuge 
  centrifuge: ^0.7.0
  # Url Launcher
  url_launcher: ^6.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  stacked_generator: ^0.5.1
  build_runner: ^2.1.2
  freezed:
  json_serializable:
  mockito:

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

    - assets/lottie/

