name: zc_desktop_flutter
description: Zuri Chat Desktop App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD
  freezed_annotation:
  json_annotation:
=======

>>>>>>> dcec163b2aa48fca0720c862ec44af5131f1a300
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^0.22.0
  google_fonts: ^2.1.0
  
  # stacked 
  stacked: ^2.2.5
  stacked_services:
  get_it: ^7.2.0
  logger: ^1.0.0
<<<<<<< HEAD
  get_it: ^7.2.0


=======
  bitsdojo_window: ^0.1.1+1
>>>>>>> dcec163b2aa48fca0720c862ec44af5131f1a300

  # local storage
  shared_preferences: ^2.0.7
  dio: ^4.0.0
  

  # ui package for the whole app
  zcdesk_ui:
    path: packages/zcdesk_ui


dev_dependencies:
  flutter_test:
    sdk: flutter
  stacked_generator: ^0.5.1
  build_runner:
<<<<<<< HEAD
  freezed: 
  json_serializable:
=======
  analyzer: 1.5.0
>>>>>>> dcec163b2aa48fca0720c862ec44af5131f1a300


flutter:
  uses-material-design: true
  assets:
    - assets/images/

    - assets/images/facebook.svg
    - assets/images/google.svg
    - assets/images/twitter.svg

    - assets/images/widgetImages/
 

 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
