name: zc_desktop_flutter
description: Zuri Chat Desktop App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^0.22.0
  google_fonts: ^2.1.0
  logger: ^1.0.0
  shared_preferences: ^2.0.7
  stacked: ^2.2.5
  stacked_services: null
  zcdesk_ui:
    path: packages/zcdesk_ui

dev_dependencies:
  build_runner: null
  flutter_test:
    sdk: flutter
  stacked_generator: ^0.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/facebook.svg
    - assets/images/google.svg
    - assets/images/twitter.svg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
